baseurl = "https://example.org/"
title = "Giacomo Sabatini - Artist Portfolio"
theme = "hugo-creative-portfolio-theme"
languageCode = "en-us"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""

[taxonomies]
author = "authors"
year= "years"
project-type = "project_types"
technique= "techniques"
software= "softwares"
skill = "skills"
pic = "pics"
description = "descriptions"


[markup.goldmark.renderer]
unsafe= true
# this allows user to use html code inside a markdown file. For examples to add images of a specific size, since markdown code does not cover this function.

[params]
  # Style options: default (pink), blue, green, pink, red, sea, violet
  # Use custom.css for your custom styling
  style = "seadark"
  # description = "Describe your website"
  # copyright = "&copy;2016 Your name or company"
  sidebarAbout = [

    "Sono un 3D Generalist e un illustratore, laureato nel corso di Visual and Motion Design all'Accademia di Belle Arti di Urbino"
  ]
  # Contact page
     # Since this template is static, the contact form uses www.formspree.io as a
     # proxy. The form makes a POST request to their servers to send the actual
     # email. Visitors can send up to a 1000 emails each month for free.
     #
     # What you need to do for the setup?
     #
     # - set your email address under 'email' below
     # - upload the generated site to your server
     # - send a dummy email yourself to confirm your account
     # - click the confirm link in the email from www.formspree.io
     # - you're done. Happy mailing!
  email = "sabatini.giacomo.p@gmail.com"

    # Optional Matomo analytics (formerly piwik)
      # [params.analytics.matomo]
      #  URL = "https://stats.example.com"
      #  ID = "42"
      #  # Track all subdomains with "*.example.com" (Optional)
      #  domain = "www.example.com"
      #  # Optional integrity check hash
      #  hash = ""

  # Nav links in the side bar
  [[params.navlinks]]
  name = "Home"
  url = "/portfolio/"
  home = true

  [[params.navlinksportfolio]]
  name = "Modeling"
  url = "techniques/modeling/"

  [[params.navlinksportfolio]]
  name = "Animation"
  url = "techniques/animation/"
  [[params.navlinksportfolio]]
  name = "Animation Shorts"
  url = "project_types/animation-short/"

  [[params.navlinks]]
  name = "About"
  url = "about/"


  [params.social]

  email         = "sabatini.giacomo.p@gmail.com"
  linkedin      = "https://www.linkedin.com/in/giacomo-sabatini-580b6277/"
  instagram     = "https://www.instagram.com/giaco.saba.anim/"
